### ISSUE TITLE
运行时异常

### ISSUE THREAD

**Issue by peidw** [ppaanngggg/JavaCTP#1]
运行时报：
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.freethink.ctp.ctpJNI.swig_module_init()V
        at com.freethink.ctp.ctpJNI.swig_module_init(Native Method)
        at com.freethink.ctp.ctpJNI.<clinit>(ctpJNI.java:7481)
        at com.freethink.ctp.CThostFtdcMdApi.CreateFtdcMdApi(CThostFtdcMdApi.java:45)
        at com.freethink.fkctp.TestMd.main(TestMd.java:10)
有解吗？
运行sh如下：
java -Xms128m -Xmx512m -XX:MaxPermSize=512m -Djava.library.path=/usr/local/lib -jar ctp-swig-1.0.jar

**Comment by ppaanngggg** [comment]
可以看一下代码吗？

**Comment by peidw** [comment]
package com.freethink.fkctp;

import com.freethink.ctp.CThostFtdcMdApi;

/**
 * Created by peidw on 2016/6/8.
 */
public class TestMd {
    public static void main(String[] args) throws Throwable {
        CThostFtdcMdApi mdApi = CThostFtdcMdApi.CreateFtdcMdApi("tcp://180.168.146.187:10010");
        //System.out.println(MdApi.GetApiVersion());
        mdApi.Init();
        System.out.println(mdApi.GetTradingDay());

    }
}

**Comment by peidw** [comment]
ppaanngggg  能否共享 一下，相关例子的代码

**Comment by peidw** [comment]
@ppaanngggg 
建个QQ群，推广一下这项目

**Comment by peidw** [comment]
peidw@p-ubuntu:~/ctp-swig$ sh runctp.sh
RuntimeError:can not open CFlow file in line 256 of file ../../source/userapi/ThostFtdcUserApiImplBase.cpp
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb57a9d31b1, pid=2022, tid=140417745458944
#
# JRE version: OpenJDK Runtime Environment (7.0_91-b02) (build 1.7.0_91-b02)
# Java VM: OpenJDK 64-Bit Server VM (24.91-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.3
# Distribution: Ubuntu Xenial Xerus (development branch), package 7u91-2.6.3-3
# Problematic frame:
# C  [libthostmduserapi.so+0x1281b1]  CThostFtdcUserApiImplBase::CThostFtdcUserApiImplBase(char const*, CSelectReactor*, bool, bool)+0x901
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/peidw/ctp-swig/hs_err_pid2022.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by peidw** [comment]
已解决

**Comment by ppaanngggg** [comment]
@peidw 哈哈，我知道了，你flow文件的文件夹没有建对吧，我这个事情已经很久没维护了，需要建个qq群吗？

**Comment by ppaanngggg** [comment]
@peidw 话说，我有个项目是EngineCTP，很久没维护了，一直没时间，要不一起搞起来？
